### ISSUE TITLE
possible bug in Homography

### ISSUE THREAD

**Issue by Mona77** [arraiy/torchgeometry#21]
@edgarriba To calculate [homography](https://github.com/arraiy/torchgeometry/blob/a7db348c5978efc7870c649757947123bfbf78fb/torchgeometry/imgwarp.py#L173) matrix you have solved for Ah=x0 where h is [8x1] vector and then you append 1 to this vector.
 I would try solving for Ah=0 where h is [9x1] then divide each element of h by the last one. Something similar to [opencv](https://github.com/opencv/opencv/blob/master/modules/calib3d/src/fundam.cpp#L178)

Please let me know if it works.

**Comment by edgarriba** [comment]
@Mona77 this is because to transform points with the homography we need homogeneous coordinates (3x3 * 3x1). If you want you can check the maths from this tensorflow implementation:
http://kindoblue.nl/neural-network/tensorflow-homography.

I've also been comparing to OpenCV results and I get the same results.
